disabled = false
languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Commons & Code"
contentDir = "content/de"

[params]
displayName = "DE"
isoCode = "de"
rtl = false
dateFormat = "02. January 2006"
description = "Europ채ischer Think-and-Do-Tank f체r gemeinwohlorientierte Digitalisierung"

[params.author]
name = "Commons & Code"
headline = "Europ채ischer Think-and-Do-Tank f체r gemeinwohlorientierte Digitalisierung"
links = [
    { mastodon = "https://eupolicy.social/@CommonsAndCode" },
    { envelope = "mailto:contact@commons-and-code.eu" },
]
