disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Commons & Code"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "European Think-and-Do-Tank for Digitalisation for the Common Good"

[params.author]
name = "Commons & Code"
headline = "European Think-and-Do-Tank for Digitalisation for the Common Good"
links = [
    { mastodon = "https://eupolicy.social/@CommonsAndCode" },
    { bluesky = "https://bsky.app/profile/commons-and-code.eu" },
    { envelope = "mailto:contact@commons-and-code.eu" },
]
