[[main]]
none = "none"
weight = 4

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "HGcjCq2NZY"
weight = 1

[[main]]
name = "Topics"
pageRef = "topics"
identifier = "6E0c2e8NJS"
weight = 2

[[main]]
name = "About Us"
pageRef = "about-us"
identifier = "eaPwNHMpa5"
weight = 3

[[main]]
name = "Team"
pageRef = "team"
parent = "eaPwNHMpa5"
identifier = "ghnHLodQWa"
weight = 31

[[main]]
name = "Founding Declaration"
pageRef = "about-us/founding-declaration"
parent = "eaPwNHMpa5"
identifier = "SkaG3Qatwr"
weight = 32

[[main]]
name = "Statutes"
pageRef = "about-us/statutes"
parent = "eaPwNHMpa5"
identifier = "Iu3gwMIPQO"
weight = 33

[[main]]
name = "Become a Member"
pageRef = "become-a-member"
identifier = "ULBwdVXPAs"
weight = 4

  [main.params]
  class = "!rounded-md bg-primary-600 px-4 py-2 !text-neutral !no-underline hover:!bg-primary-500 dark:bg-primary-800 dark:hover:!bg-primary-700"

[[footer]]
none = "none"

[[footer]]
name = "Imprint"
pageRef = "imprint"
identifier = "7t63Gj9UqM"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "privacy-policy"
identifier = "h4xxUgWSKP"
weight = 2

[[footer]]
name = "CC BY-SA 4.0"
pageRef = "imprint"
identifier = "sFPGmJ1uOb"
weight = 3
