[[main]]
none = "none"
weight = 4

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "HGcjCq2NZY"
weight = 1

# [[main]]
# name = "Themen"
# pageRef = "themen"
# identifier = "6E0c2e8NJS"
# weight = 2

[[main]]
name = "Über Uns"
pageRef = "ueber-uns"
identifier = "eaPwNHMpa5"
weight = 3

[[main]]
name = "Team"
pageRef = "team"
parent = "eaPwNHMpa5"
identifier = "ghnHLodQWa"
weight = 31

[[main]]
name = "Gründungserklärung"
pageRef = "ueber-uns/gruendungserklaerung"
parent = "eaPwNHMpa5"
identifier = "SkaG3Qatwr"
weight = 32

[[main]]
name = "Transparenz"
pageRef = "ueber-uns/transparenz"
parent = "eaPwNHMpa5"
identifier = "51zorqp5oC"
weight = 33

[[main]]
name = "Statuten"
pageRef = "ueber-uns/statuten"
parent = "eaPwNHMpa5"
identifier = "Iu3gwMIPQO"
weight = 34

[[main]]
name = "Mitglied werden"
pageRef = "mitglied-werden"
params.class = "!rounded-md bg-primary-600 px-4 py-2 !text-neutral !no-underline hover:!bg-primary-500 dark:bg-primary-800 dark:hover:!bg-primary-700"
identifier = "ULBwdVXPAs"
weight = 4

[[footer]]
none = "none"

[[footer]]
name = "Impressum"
pageRef = "impressum"
identifier = "7t63Gj9UqM"
weight = 1

[[footer]]
name = "Datenschutz"
url = "/de/rechtliches/datenschutz"
identifier = "h4xxUgWSKP"
weight = 2

[[footer]]
name = "CC BY-SA 4.0"
pageRef = "impressum"
identifier = "sFPGmJ1uOb"
weight = 3
